name: 'Continuous Integration'
description: 'Continuous Integration flow'
inputs:
  project-build:
    description: 'Project repo'
    required: true
    default: 'repo'
  project-type:
    description: 'Project type'
    required: true
    default: 'mvn'
  project-steps:
    description: 'Project steps: start_sonarqube create_sonarqube_project build_tlx-api start_sonarscan stop_sonarscan generate_sonarqube_report stop_sonarqube'
    required: true
    default: 'all'
outputs:
  artifact:
    description: "artifact"
    value: ${{ steps.project-artifacts.outputs.jar-location }}
runs:
  using: "composite"
  steps:
    - id: project-ci
      run: ${{ github.action_path }}/ci-flow.sh ${{ inputs.project-steps }}
      shell: bash
    - id: project-artifacts
      run: echo "::set-output name=jar-location::$(echo $PROJECT_ARTIFACT)"
      shell: bash
    
    