name: 'Tlx Continuous Integration'
description: 'Tlx Continuous Integration flow'
inputs:
  project-name:
    description: 'Project repo name'
    required: true
  project-dir:
    description: 'Project dir'
    required: false
  project-package-dir:
    description: 'Project package dir'
    required: false
  project-type:
    description: 'Project type'
    required: true
    default: 'mvn'
  project-artifact:
    description: 'Project artifact path'
    required: true
  project-artifact-name:
    description: 'Project artifact name'
    required: false
  project-branch: 'develop'
    description: 'Project repo branch'
    required: false
  build-command:
    description: 'Project build command'
    required: false
  publish-docker-build-args:
    description: 'Publishing docker build arguments'
    required: false
  project-steps:
    description: 'Project steps: start_sonarqube create_sonarqube_project build start_sonarscan stop_sonarscan generate_sonarqube_report stop_sonarqube store_artifacts push_docker_image'
    required: true
    default: 'all'
outputs:
  artifact:
    description: "artifact"
    value: ${{ steps.project-artifacts.outputs.artifact-location }}
runs:
  using: "composite"
  steps:
    - id: project-ci
      run: ARTIFACT_NAME=${{ inputs.project-artifact-name }} BUILD_COMMAND=${{ inputs.build-command }} PROJECT=${{ inputs.project-name }} PROJECT_BRANCH=${{ inputs.project-branch }} PROJECT_DIR=${{ inputs.project-dir }} PROJECT_PACKAGE_DIR=${{ inputs.project-package-dir }} PROJECT_TYPE=${{ inputs.project-type }} ARTIFACT_PATH=${{ inputs.project-artifact}} ${{ github.action_path }}/ci-flow.sh ${{ inputs.project-steps }}
      shell: bash
    - id: project-artifacts
      run: echo "::set-output name=artifact-location::$(echo $ARTIFACT_PATH)"
      shell: bash
    
    
